version: "3"

dotenv:
  - .env
tasks:
  build-fe:
    cmds:
      - (cd frontend && pnpm build)
    generates:
      - frontend/dist/**/*
    sources:
      - frontend/src/**/*

  dev:
    cmd: air
    deps:
      - build-fe

  dev-api:
    cmd: air

  test:
    cmd: go test -v ./...

  db-up:
    cmd: docker run --name workpadpg -v ./pg-data:/var/lib/postgresql -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres -e POSTGRES_DB=workpadpg -p 5432:5432 -d postgres

  migrate-up:
    cmd: go tool goose -dir ./migrations/sqlite sqlite3 ./app.db up

  migrate-down:
    cmd: go tool goose -dir ./migrations/sqlite sqlite3 ./app.db down

  migrate-add:
    cmd: ./scripts/migrate-add.sh
