/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/auth'
import { Route as MainLayoutImport } from './routes/_main-layout'
import { Route as MainLayoutIndexImport } from './routes/_main-layout/index'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as MainLayoutProfileImport } from './routes/_main-layout/profile'
import { Route as MainLayoutAboutImport } from './routes/_main-layout/about'
import { Route as MainLayoutProfileScheduleImport } from './routes/_main-layout/profile/schedule'
import { Route as MainLayoutProfileFeedsImport } from './routes/_main-layout/profile/feeds'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const MainLayoutRoute = MainLayoutImport.update({
  id: '/_main-layout',
  getParentRoute: () => rootRoute,
} as any)

const MainLayoutIndexRoute = MainLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const MainLayoutProfileRoute = MainLayoutProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutAboutRoute = MainLayoutAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutProfileScheduleRoute = MainLayoutProfileScheduleImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => MainLayoutProfileRoute,
} as any)

const MainLayoutProfileFeedsRoute = MainLayoutProfileFeedsImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => MainLayoutProfileRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main-layout': {
      id: '/_main-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainLayoutImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_main-layout/about': {
      id: '/_main-layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainLayoutAboutImport
      parentRoute: typeof MainLayoutImport
    }
    '/_main-layout/profile': {
      id: '/_main-layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainLayoutProfileImport
      parentRoute: typeof MainLayoutImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_main-layout/': {
      id: '/_main-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutIndexImport
      parentRoute: typeof MainLayoutImport
    }
    '/_main-layout/profile/feeds': {
      id: '/_main-layout/profile/feeds'
      path: '/feeds'
      fullPath: '/profile/feeds'
      preLoaderRoute: typeof MainLayoutProfileFeedsImport
      parentRoute: typeof MainLayoutProfileImport
    }
    '/_main-layout/profile/schedule': {
      id: '/_main-layout/profile/schedule'
      path: '/schedule'
      fullPath: '/profile/schedule'
      preLoaderRoute: typeof MainLayoutProfileScheduleImport
      parentRoute: typeof MainLayoutProfileImport
    }
  }
}

// Create and export the route tree

interface MainLayoutProfileRouteChildren {
  MainLayoutProfileFeedsRoute: typeof MainLayoutProfileFeedsRoute
  MainLayoutProfileScheduleRoute: typeof MainLayoutProfileScheduleRoute
}

const MainLayoutProfileRouteChildren: MainLayoutProfileRouteChildren = {
  MainLayoutProfileFeedsRoute: MainLayoutProfileFeedsRoute,
  MainLayoutProfileScheduleRoute: MainLayoutProfileScheduleRoute,
}

const MainLayoutProfileRouteWithChildren =
  MainLayoutProfileRoute._addFileChildren(MainLayoutProfileRouteChildren)

interface MainLayoutRouteChildren {
  MainLayoutAboutRoute: typeof MainLayoutAboutRoute
  MainLayoutProfileRoute: typeof MainLayoutProfileRouteWithChildren
  MainLayoutIndexRoute: typeof MainLayoutIndexRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutAboutRoute: MainLayoutAboutRoute,
  MainLayoutProfileRoute: MainLayoutProfileRouteWithChildren,
  MainLayoutIndexRoute: MainLayoutIndexRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof MainLayoutRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/about': typeof MainLayoutAboutRoute
  '/profile': typeof MainLayoutProfileRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/': typeof MainLayoutIndexRoute
  '/profile/feeds': typeof MainLayoutProfileFeedsRoute
  '/profile/schedule': typeof MainLayoutProfileScheduleRoute
}

export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/about': typeof MainLayoutAboutRoute
  '/profile': typeof MainLayoutProfileRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/': typeof MainLayoutIndexRoute
  '/profile/feeds': typeof MainLayoutProfileFeedsRoute
  '/profile/schedule': typeof MainLayoutProfileScheduleRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_main-layout': typeof MainLayoutRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_main-layout/about': typeof MainLayoutAboutRoute
  '/_main-layout/profile': typeof MainLayoutProfileRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_main-layout/': typeof MainLayoutIndexRoute
  '/_main-layout/profile/feeds': typeof MainLayoutProfileFeedsRoute
  '/_main-layout/profile/schedule': typeof MainLayoutProfileScheduleRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/auth'
    | '/about'
    | '/profile'
    | '/auth/login'
    | '/'
    | '/profile/feeds'
    | '/profile/schedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/about'
    | '/profile'
    | '/auth/login'
    | '/'
    | '/profile/feeds'
    | '/profile/schedule'
  id:
    | '__root__'
    | '/_main-layout'
    | '/auth'
    | '/_main-layout/about'
    | '/_main-layout/profile'
    | '/auth/login'
    | '/_main-layout/'
    | '/_main-layout/profile/feeds'
    | '/_main-layout/profile/schedule'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  MainLayoutRoute: MainLayoutRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_main-layout",
        "/auth"
      ]
    },
    "/_main-layout": {
      "filePath": "_main-layout.tsx",
      "children": [
        "/_main-layout/about",
        "/_main-layout/profile",
        "/_main-layout/"
      ]
    },
    "/auth": {
      "filePath": "auth.tsx",
      "children": [
        "/auth/login"
      ]
    },
    "/_main-layout/about": {
      "filePath": "_main-layout/about.tsx",
      "parent": "/_main-layout"
    },
    "/_main-layout/profile": {
      "filePath": "_main-layout/profile.tsx",
      "parent": "/_main-layout",
      "children": [
        "/_main-layout/profile/feeds",
        "/_main-layout/profile/schedule"
      ]
    },
    "/auth/login": {
      "filePath": "auth/login.tsx",
      "parent": "/auth"
    },
    "/_main-layout/": {
      "filePath": "_main-layout/index.tsx",
      "parent": "/_main-layout"
    },
    "/_main-layout/profile/feeds": {
      "filePath": "_main-layout/profile/feeds.tsx",
      "parent": "/_main-layout/profile"
    },
    "/_main-layout/profile/schedule": {
      "filePath": "_main-layout/profile/schedule.tsx",
      "parent": "/_main-layout/profile"
    }
  }
}
ROUTE_MANIFEST_END */
