@host=localhost:8000

# @name login
POST http://{{host}}/auth/login
Content-Type: application/json

{
  "email": "email@site.com",
  "password": "stringst"
}

###
GET http://{{host}}/auth/me
Authorization: Bearer {{login.response.body.accessToken}}


###
GET http://{{host}}/auth/signup
Content-Type: application/json

{
  "email": "email@site.com",
  "password": "stringst",
  "password2": "stringst"
}
